baseURL = 'https://alex-akselrod.pages.dev'
languageCode = 'ru-RU'
title = 'Публичные заметки'
theme = 'risotto'
# Automatically add content sections to main menu
#sectionPagesMenu = "main"
[params.theme]
palette = "base16-dark"
[menu]    
  [[menu.main]]
    identifier = "scrum"
    name = "Scrum"
    url = "/posts/scrum"
    weight = 10
    
  [[menu.main]]
    identifier = "q-planning"
    name = "Планирование"
    url = "/posts/quarter-planning"
    weight = 10
# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true
