baseURL = 'https://alex-akselrod.pages.dev'
languageCode = 'ru-RU'
title = 'Публичные заметки'
theme = 'risotto'
# Automatically add content sections to main menu
#sectionPagesMenu = "main"
[params.theme]
palette = "base16-dark"
[menu]    
  [[menu.main]]
    identifier = "processes"
    name = "Процессы"
    url = "/processes/"
    weight = 10
  [[menu.main]]
    identifier = "scrum"
    name = "Scrum"
    url = "/processes/scrum/"
    weight = 10
    parent = "processes"
  [[menu.main]]
    identifier = "q-planning"
    name = "Планирование"
    url = "/processes/quarter-planning"
    weight = 10
    parent = "processes"    
  [[menu.main]]
    identifier = "arch-review"
    name = "Арх ревью"
    url = "/processes/arch-review"
    weight = 10
    parent = "processes"
  [[menu.main]]
    identifier = "private"
    name = "Частное"
    url = "/private"
    weight = 10
# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true
